# RUN THIS TO DEPLOY TO VERGIL!
# YOU WILL BE PROMPTED FOR PW, UNLESS YOU SET UP SSH KEYS
# NOTE: THIS WILL DEPLOY MANUALLY, BUT THE WEBSITE SHOULD
# BE AUTOMATICALLY DEPLOYED TO VERGIL WHENEVER YOU PUSH TO MAIN

npm run build-for-vergil
scp -r ./dist/* hcpuw@vergil.u.washington.edu:public_html
